Repository AlbertHernandez/github-action-nodejs-template, pull requests merged in 2024-09, with the labels that each got.

#250 chore(perm-dev): Updated permissions assigned to GithubToken
  .github/workflows/assign-me.yml
Labels: 🚀 CI/CD, ignore-for-release

#259 ci: added auto updating of inputs, outputs in README
  .github/workflows/generate-docs.yml
  README.md
  action.yml
  release-please-config.json
Labels: 🚀 CI/CD, 📝 Documentation, 🚀 Feature

#283 chore(main): release 0.11.1
  .release-please-manifest.json
  CHANGELOG.md
  dist/index.js
  package-lock.json
  package.json
Labels: 📦 Dependencies, 🥳 size/s, ignore-for-release, autorelease: pending
